%matplotlib inline

# Numpy 基础学习

## ndarry:多维数组对象
  numpy最重要的一种数据对象，可以进行整块数据运算。

In [2]:
%cd ch04/

/Users/apple/workspace/DataSince/pydata-book/ch04


In [3]:
import numpy as np
from numpy.random import randn 

In [6]:
data = randn(2,3) #随机创建一个ndarry数组

In [7]:
data

array([[ 0.81864017,  1.22267661,  1.98360398],
       [-1.34101899,  0.51180943,  2.5973447 ]])

In [8]:
data * 10 #语法和标量元素之间的运算一个

array([[  8.18640173,  12.22676605,  19.83603978],
       [-13.41018987,   5.11809427,  25.97344697]])

In [9]:
data + data

array([[ 1.63728035,  2.44535321,  3.96720796],
       [-2.68203797,  1.02361885,  5.19468939]])

ndarry 是一个同构数据多维容器，其中所有元素必须是相同类型。

In [10]:
data.shape #shape是表示各维度大小的元组

(2, 3)

In [11]:
data.dtype #dtype说明数组数据类型的对象

dtype('float64')

## ndarray创建
使用array函数创建，该函数接受一切序列型对象

In [12]:
data1 = [1,2,3,4,5]

In [13]:
naray1 = np.array(data1)

In [14]:
naray1

array([1, 2, 3, 4, 5])

In [15]:
np.zeros(10) #创建全0数组
np.ones(10)  #创建全1数组

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [20]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
np.empty((2,3,1)) #empty 有时候会初始化垃圾值，并不一定是0

array([[[ 0.],
        [ 0.],
        [ 0.]],

       [[ 0.],
        [ 0.],
        [ 0.]]])

In [23]:
np.arange(15) #类似内置的range,返回ndarry不是列表

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## ndarry数据类型
dtype是numpy的一个对象，有ndarry将一块内存解释为特定数据类型所需的信息。

In [24]:
arr1 = np.array([2,3],dtype=np.float64) #除非显式声明dtype，否则numpy会自动选择合适的数据类型

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr = np.array([1,2,3,4,5,6])

In [28]:
arr

array([1, 2, 3, 4, 5, 6])

In [30]:
arr.astype(np.float64) #astype 显式转换数据类型，创建新的数组（拷贝原数组）

array([ 1.,  2.,  3.,  4.,  5.,  6.])

## 数组标量间运算
即矢量化运算，可以不用通过循环就可以对数据执行批量运算

In [2]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [3]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [4]:
arr - arr #大小相等数组间任何算术运算都会运用到元素级

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [5]:
1+arr  #与标量运算也会传播到各个元素

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

## 索引和切片
### 一维数组

In [8]:
arr = np.arange(10)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]  #一维数组操作和python列表功能差不多

5

In [11]:
arr[5:8]

array([5, 6, 7])

In [12]:
arr[3:6] = 10

In [13]:
arr

array([ 0,  1,  2, 10, 10, 10,  6,  7,  8,  9])

*与列表的区别：数组切片是原始数组的视图，所有操作都在原始数组上，数据不会被复制。*

In [14]:
arr_slice = arr[1:4]

In [15]:
arr_slice

array([ 1,  2, 10])

In [16]:
arr_slice[1] = 1122

In [17]:
arr

array([   0,    1, 1122,   10,   10,   10,    6,    7,    8,    9])

In [18]:
arr_slice = arr[1:4].copy() #如需复制需要显式说明

### 多维数组
各索引位置上不再是标量而是数组

In [19]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
arr2d[2] 

array([7, 8, 9])

In [21]:
arr2d[2,1]  #二维矩阵单个元素提取

8

### 高维数组切片索引

In [22]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2d[:1]  #默认以0轴进行切片

array([[1, 2, 3]])

In [24]:
arr2d[:2,:2]  #一次传入多个切片

array([[1, 2],
       [4, 5]])

## 布尔索引

In [2]:
names = np.array(['a','b','c','a','d'])

In [3]:
names=='a'

array([ True, False, False,  True, False], dtype=bool)

In [4]:
data = randn(5,3)

In [5]:
data

array([[ 1.00835702, -0.67904266, -0.44755107],
       [-1.55372947,  0.74991865, -2.54631379],
       [-0.58777312, -0.56724948, -0.51350374],
       [-1.82055349,  0.33002027, -0.23504056],
       [ 0.68790517,  1.04794177,  0.49661298]])

In [6]:
data[names=='a']  #布尔型数组长度必须跟被索引的轴长度一致

array([[ 1.00835702, -0.67904266, -0.44755107],
       [-1.82055349,  0.33002027, -0.23504056]])

## 花式索引
利用整数数组进行索引
花式索引将数据复制到新的数组

In [8]:
arr = np.empty((8,4))

In [12]:
for i in range(8):
    arr[i] = i+1

In [14]:
arr

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.]])

In [15]:
arr[[3,2,6]] #以特定顺序选取行子集，传入用于指定顺序的整数列表，使用负数会从尾部开始取

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 7.,  7.,  7.,  7.]])

## 数组转置和轴对换
返回源数组视图不产生新的数组

In [16]:
arr = np.arange(15).reshape((3,5))

In [17]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [20]:
arr #返回源数组视图

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 数据处理 计算sqrt(x^2+y^2)

In [8]:
points = np.arange(-5,5,0.01)

In [9]:
xs,ys = np.meshgrid(points,points)

In [10]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [11]:
import matplotlib.pyplot as plt

In [12]:
z = np.sqrt(xs**2+ys**2)

In [13]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [14]:
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()

## 数学和统计方法

In [15]:
arr = np.random.randn(5,4) #正态分布数据

In [16]:
arr.mean()  #均值

-0.43473018750795334

In [17]:
np.mean(arr)

-0.43473018750795334

In [18]:
arr

array([[-1.58926742, -0.1632255 , -1.48664356, -0.12766491],
       [-0.97934835, -0.23099791, -0.30055414,  0.32489684],
       [ 1.17316358, -1.63821456, -0.53605441,  0.97179719],
       [ 0.18209741, -3.88646239, -0.26441447,  0.66892478],
       [ 0.74658754, -1.10206432,  0.22823898, -0.68539814]])

In [19]:
arr.sum()

-8.6946037501590663

In [20]:
arr.mean(axis=0)

array([-0.09335345, -1.40419294, -0.47188552,  0.23051115])

In [21]:
arr.mean(axis=1)

array([-0.84170034, -0.29650089, -0.00732705, -0.82496367, -0.20315899])

In [22]:
arr.std()

1.1280097319439752

In [23]:
arr.min()

-3.8864623914198235

## 排序
可通过sort方法进行排序

In [24]:
arr = randn(5,3)

In [26]:
arr

array([[-0.85121181, -1.18395541,  0.7583028 ],
       [-1.25808424, -1.18967687, -2.04438527],
       [-0.479327  ,  0.3450897 , -1.63062614],
       [ 0.88562111,  0.03362126,  1.29185623],
       [-0.99682785,  0.61020649,  1.903782  ]])

In [33]:
arr[:,1]
#arr.sort(1)  #多维数组可在任意轴上排序

array([-0.85121181, -1.25808424, -0.479327  ,  0.88562111,  0.61020649])

In [28]:
arr

array([[-1.18395541, -0.85121181,  0.7583028 ],
       [-2.04438527, -1.25808424, -1.18967687],
       [-1.63062614, -0.479327  ,  0.3450897 ],
       [ 0.03362126,  0.88562111,  1.29185623],
       [-0.99682785,  0.61020649,  1.903782  ]])

In [30]:
arr[2,:]

array([-1.63062614, -0.479327  ,  0.3450897 ])

# 用于数组的文件输入输出
numpy 能读写磁盘文本数据或二进制数据。
## 数组以二进制保存

In [2]:
arr = np.arange(10)

In [3]:
np.save("test_save",arr) #保存

In [4]:
test = np.load("test_save.npy") #读取

In [5]:
test

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
%cd /Users/apple/workspace/MachineLearning/Python/Logistic\ Regression

/Users/apple/workspace/MachineLearning/Python/Logistic Regression


In [2]:
%ls

LogistinRegression.py  ex2data1.txt


In [7]:
data = np.loadtxt("ex2data1.txt",delimiter=",")

In [8]:
data


array([[ 34.62365962,  78.02469282,   0.        ],
       [ 30.28671077,  43.89499752,   0.        ],
       [ 35.84740877,  72.90219803,   0.        ],
       [ 60.18259939,  86.3085521 ,   1.        ],
       [ 79.03273605,  75.34437644,   1.        ],
       [ 45.08327748,  56.31637178,   0.        ],
       [ 61.10666454,  96.51142588,   1.        ],
       [ 75.02474557,  46.55401354,   1.        ],
       [ 76.0987867 ,  87.42056972,   1.        ],
       [ 84.43281996,  43.53339331,   1.        ],
       [ 95.86155507,  38.22527806,   0.        ],
       [ 75.01365839,  30.60326323,   0.        ],
       [ 82.30705337,  76.4819633 ,   1.        ],
       [ 69.36458876,  97.71869196,   1.        ],
       [ 39.53833914,  76.03681085,   0.        ],
       [ 53.97105215,  89.20735014,   1.        ],
       [ 69.07014406,  52.74046973,   1.        ],
       [ 67.94685548,  46.67857411,   0.        ],
       [ 70.66150955,  92.92713789,   1.        ],
       [ 76.97878373,  47.57596

In [9]:
data[:,0]

array([ 34.62365962,  30.28671077,  35.84740877,  60.18259939,
        79.03273605,  45.08327748,  61.10666454,  75.02474557,
        76.0987867 ,  84.43281996,  95.86155507,  75.01365839,
        82.30705337,  69.36458876,  39.53833914,  53.97105215,
        69.07014406,  67.94685548,  70.66150955,  76.97878373,
        67.37202755,  89.67677575,  50.53478829,  34.21206098,
        77.92409145,  62.27101367,  80.19018075,  93.1143888 ,
        61.83020602,  38.7858038 ,  61.37928945,  85.40451939,
        52.10797973,  52.04540477,  40.23689374,  54.63510555,
        33.91550011,  64.17698887,  74.78925296,  34.18364003,
        83.90239366,  51.54772027,  94.44336777,  82.36875376,
        51.04775177,  62.22267576,  77.19303493,  97.77159928,
        62.0730638 ,  91.5649745 ,  79.94481794,  99.27252693,
        90.54671411,  34.52451385,  50.28649612,  49.58667722,
        97.64563396,  32.57720017,  74.24869137,  71.79646206,
        75.39561147,  35.28611282,  56.2538175 ,  30.05