In [1]:
%matplotlib inline

# Numpy 基础学习

## ndarry:多维数组对象
  numpy最重要的一种数据对象，可以进行整块数据运算。

In [2]:
%cd ch04/

/Users/apple/workspace/DataSince/pydata-book/ch04


In [5]:
import numpy as np
from numpy.random import randn 

In [6]:
data = randn(2,3) #随机创建一个ndarry数组

In [7]:
data

array([[ 0.81864017,  1.22267661,  1.98360398],
       [-1.34101899,  0.51180943,  2.5973447 ]])

In [8]:
data * 10 #语法和标量元素之间的运算一个

array([[  8.18640173,  12.22676605,  19.83603978],
       [-13.41018987,   5.11809427,  25.97344697]])

In [9]:
data + data

array([[ 1.63728035,  2.44535321,  3.96720796],
       [-2.68203797,  1.02361885,  5.19468939]])

ndarry 是一个同构数据多维容器，其中所有元素必须是相同类型。

In [10]:
data.shape #shape是表示各维度大小的元组

(2, 3)

In [11]:
data.dtype #dtype说明数组数据类型的对象

dtype('float64')

## ndarray创建
使用array函数创建，该函数接受一切序列型对象

In [12]:
data1 = [1,2,3,4,5]

In [13]:
naray1 = np.array(data1)

In [14]:
naray1

array([1, 2, 3, 4, 5])

In [15]:
np.zeros(10) #创建全0数组
np.ones(10)  #创建全1数组

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [20]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
np.empty((2,3,1)) #empty 有时候会初始化垃圾值，并不一定是0

array([[[ 0.],
        [ 0.],
        [ 0.]],

       [[ 0.],
        [ 0.],
        [ 0.]]])

In [23]:
np.arange(15) #类似内置的range,返回ndarry不是列表

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## ndarry数据类型
dtype是numpy的一个对象，有ndarry将一块内存解释为特定数据类型所需的信息。

In [24]:
arr1 = np.array([2,3],dtype=np.float64) #除非显式声明dtype，否则numpy会自动选择合适的数据类型

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr = np.array([1,2,3,4,5,6])

In [28]:
arr

array([1, 2, 3, 4, 5, 6])

In [30]:
arr.astype(np.float64) #astype 显式转换数据类型，创建新的数组（拷贝原数组）

array([ 1.,  2.,  3.,  4.,  5.,  6.])